from __future__ import annotations

import re
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

from skills.bmad_create_specialist.scripts import generate


def _read_pyproject(repo_root: Path) -> str:
    return (repo_root / "pyproject.toml").read_text(encoding="utf-8")


def test_appends_row_at_wet_run(temp_repo_root: Path, make_request) -> None:
    before = _read_pyproject(temp_repo_root)
    before_lines = before.splitlines()

    generate.generate_specialist(
        make_request(name="fakeauto5", repo_root=temp_repo_root),
    )

    after = _read_pyproject(temp_repo_root)
    after_lines = after.splitlines()
    target = "app.specialists.fakeauto5.graph -> app.gates.resume_api"
    assert target in after
    assert len(after_lines) == len(before_lines) + 1
    assert after.count(target) == 1
    assert "app.specialists.texas.graph -> app.gates.resume_api" in after


def test_idempotent_on_rerun(temp_repo_root: Path, make_request) -> None:
    generate.generate_specialist(make_request(name="fakeauto5", repo_root=temp_repo_root))
    pyproject_after_first = _read_pyproject(temp_repo_root)

    generate.generate_specialist(
        make_request(name="fakeauto5", force=True, repo_root=temp_repo_root),
    )
    pyproject_after_second = _read_pyproject(temp_repo_root)

    assert pyproject_after_second == pyproject_after_first


def test_dry_run_does_not_mutate(temp_repo_root: Path, make_request) -> None:
    before = _read_pyproject(temp_repo_root)
    result = generate.generate_specialist(
        make_request(name="fakeauto5", dry_run=True, repo_root=temp_repo_root),
    )
    after = _read_pyproject(temp_repo_root)

    assert result.dry_run is True
    assert result.written_files == tuple()
    assert result.plan_notes == (
        "would append C3 ignore_imports row: "
        "app.specialists.fakeauto5.graph -> app.gates.resume_api",
    )
    assert after == before


def test_atomic_rollback_on_pyproject_failure(
    temp_repo_root: Path, make_request, monkeypatch: pytest.MonkeyPatch
) -> None:
    before = _read_pyproject(temp_repo_root)
    original_write = generate._write_text

    def _failing_write(path: Path, content: str) -> None:
        if path.name == "pyproject.toml":
            raise OSError("simulated pyproject failure")
        original_write(path, content)

    monkeypatch.setattr(generate, "_write_text", _failing_write)

    with pytest.raises(generate.GeneratorInputError, match="atomic emission failed"):
        generate.generate_specialist(make_request(name="fakeauto5", repo_root=temp_repo_root))

    assert _read_pyproject(temp_repo_root) == before
    specialist_root = temp_repo_root / "app" / "specialists" / "fakeauto5"
    assert not (specialist_root / "graph.py").exists()
    assert not (specialist_root / "state.py").exists()


def test_atomic_rollback_on_malformed_c3_block(temp_repo_root: Path, make_request) -> None:
    malformed = _read_pyproject(temp_repo_root).replace(
        (
            'name = "Contract C3 — only the three authorized bridge modules '
            'may import app.gates.resume_api (D3)"'
        ),
        'name = "Contract CX placeholder"',
    )
    (temp_repo_root / "pyproject.toml").write_text(malformed, encoding="utf-8")

    with pytest.raises(
        generate.GeneratorInputError,
        match="does not contain a Contract C3 importlinter block",
    ):
        generate.generate_specialist(make_request(name="fakeauto5", repo_root=temp_repo_root))

    assert not (temp_repo_root / "app" / "specialists" / "fakeauto5").exists()


def test_comment_marker_shape(temp_repo_root: Path, make_request) -> None:
    generate.generate_specialist(make_request(name="fakeauto5", repo_root=temp_repo_root))
    pyproject = _read_pyproject(temp_repo_root)

    pattern = re.compile(
        r'^\s*"app\.specialists\.fakeauto5\.graph -> app\.gates\.resume_api",'
        r"  # generated by bmad-create-specialist for fakeauto5$",
        re.MULTILINE,
    )
    assert pattern.search(pyproject)


def test_lint_imports_clean_after_emit(temp_repo_root: Path, make_request) -> None:
    generate.generate_specialist(make_request(name="fakeauto5", repo_root=temp_repo_root))
    for specialist_name in ("irene", "kira", "texas"):
        specialist_root = temp_repo_root / "app" / "specialists" / specialist_name
        specialist_root.mkdir(parents=True, exist_ok=True)
        (specialist_root / "__init__.py").write_text("", encoding="utf-8")
        (specialist_root / "graph.py").write_text(
            "from app.gates.resume_api import resume_from_verdict\n",
            encoding="utf-8",
        )
    lint_imports_cmd = shutil.which("lint-imports")
    if lint_imports_cmd is None:
        lint_imports_cmd = str(Path(sys.executable).with_name("lint-imports.exe"))
    if not Path(lint_imports_cmd).exists():
        lint_imports_cmd = str(Path(sys.executable).with_name("lint-imports"))

    completed = subprocess.run(
        [lint_imports_cmd],
        cwd=temp_repo_root,
        shell=False,
        timeout=30,
        text=True,
        capture_output=True,
        check=False,
    )
    assert completed.returncode == 0, completed.stdout + "\n" + completed.stderr
    assert "Contracts: 3 kept, 0 broken." in (completed.stdout + completed.stderr)
