from __future__ import annotations

import re
from pathlib import Path

from skills.bmad_create_specialist.scripts import generate


def _c3_row(name: str) -> str:
    return f'"app.specialists.{name}.graph -> app.gates.resume_api",'


def _insert_c3_row(pyproject_path: Path, name: str) -> None:
    text = pyproject_path.read_text(encoding="utf-8")
    marker = '    "app.specialists.texas.graph -> app.gates.resume_api",\n]\n'
    row = f"    {_c3_row(name)}  # generated by bmad-create-specialist for {name}\n"
    pyproject_path.write_text(text.replace(marker, f"{marker[:-2]}{row}]\n", 1), encoding="utf-8")


def _ignore_row_count(pyproject_path: Path) -> int:
    return sum(
        1
        for line in pyproject_path.read_text(encoding="utf-8").splitlines()
        if " -> app.gates.resume_api" in line
    )


def test_retire_removes_c3_row_for_known_name(temp_repo_root: Path) -> None:
    pyproject_path = temp_repo_root / "pyproject.toml"
    _insert_c3_row(pyproject_path, "tmp_x")
    before_count = _ignore_row_count(pyproject_path)

    result = generate.retire_specialist("tmp_x", repo_root=temp_repo_root)

    text = pyproject_path.read_text(encoding="utf-8")
    assert result.row_removed is True
    assert _ignore_row_count(pyproject_path) == before_count - 1
    assert _c3_row("tmp_x") not in text


def test_retire_idempotent_when_row_absent(temp_repo_root: Path, monkeypatch, capsys) -> None:
    pyproject_path = temp_repo_root / "pyproject.toml"
    before_count = _ignore_row_count(pyproject_path)
    monkeypatch.setattr(generate, "_repo_root", lambda: temp_repo_root)

    exit_code = generate.main(["--retire", "tmp_x"])

    captured = capsys.readouterr()
    assert exit_code == 0
    assert _ignore_row_count(pyproject_path) == before_count
    assert re.match(r"^row for \S+ not present, no-op$", captured.out.strip())


def test_retire_does_not_touch_specialist_tree(temp_repo_root: Path) -> None:
    specialist_dir = temp_repo_root / "app" / "specialists" / "tmp_x"
    specialist_dir.mkdir(parents=True)
    (specialist_dir / "graph.py").write_text("# keep me\n", encoding="utf-8")
    before_paths = sorted(path.relative_to(specialist_dir) for path in specialist_dir.rglob("*"))

    result = generate.retire_specialist("tmp_x", repo_root=temp_repo_root)

    after_paths = sorted(path.relative_to(specialist_dir) for path in specialist_dir.rglob("*"))
    assert result.row_removed is False
    assert specialist_dir.is_dir()
    assert after_paths == before_paths
    assert (specialist_dir / "graph.py").read_text(encoding="utf-8") == "# keep me\n"


def test_retire_mutually_exclusive_with_name(capsys) -> None:
    exit_code = generate.main(
        [
            "--name",
            "foo",
            "--retire",
            "bar",
            "--mcp",
            "none",
            "--expertise-tier",
            "L5-toy",
        ]
    )

    captured = capsys.readouterr()
    assert exit_code != 0
    assert re.search(r"--name.*--retire|--retire.*--name", captured.err)
