"""Story 43-5 — plan-unit + estimator + run-constants renderers (+ the gate→renderer bridge).

Replay-only against the SYNTHETIC fixtures under ``tests/fixtures/hil_projector/``
(``poll-plan-unit-synthetic.json`` / ``poll-estimator-synthetic.json`` /
``poll-run-constants-synthetic.json``), each generated by invoking the REAL
``poll_surface.display_*`` function against a constructed decision card / model
(zero live spend).

Proves:

* **AC-1** — three bespoke renderers table each gate's content on its merits
  (**G1A plan-unit ratification**, **G1.5 run-budget estimator**, **G1.5
  run-constants lock**), never the generic ``Field | Value`` dump.
* **AC-2 (the bridge)** — the paused-gate identifiers route through
  ``GATE_TO_CONTENT_TYPE`` to the BESPOKE renderers, both at the resolver level AND
  end-to-end through ``trial.py::_emit_gate_surface_if_paused``. The two G1.5 content
  types share the "G1.5" gate string, so the disambiguating routing key is the
  poll-surface ``surface_id`` (mirrors 43-3's G2B/G2M split).
* **AC-4** — all three moved allowlist → registry (disjoint invariant holds).
* **AC-5** — the renderers stay stdlib-pure and tolerate BOTH the ``display_*``
  return shape AND a bare card / payload body.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest

import app.marcus.cli.trial as trial
from app.marcus.cli.hil_tabular_projector import (
    KNOWN_UNRENDERED_ALLOWLIST,
    get_renderer,
    registered_content_types,
    render_estimator,
    render_gate_content,
    render_generic_gate_content,
    render_plan_unit,
    render_run_constants,
    resolve_content_type,
)

FIXTURES = Path(__file__).resolve().parents[3] / "tests" / "fixtures" / "hil_projector"
PLAN_UNIT_FIXTURE = FIXTURES / "poll-plan-unit-synthetic.json"
ESTIMATOR_FIXTURE = FIXTURES / "poll-estimator-synthetic.json"
RUN_CONSTANTS_FIXTURE = FIXTURES / "poll-run-constants-synthetic.json"


def _load(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


# ---------------------------------------------------------------------------
# AC-4 — allowlist → registry moves.
# ---------------------------------------------------------------------------


def test_renderers_are_registered_and_off_the_allowlist() -> None:
    """AC-4: ``plan_unit`` / ``estimator`` / ``run_constants`` dispatch to bespoke
    renderers and have LEFT the shrink-only allowlist (disjoint invariant requires
    the deletion)."""
    for content_type in ("plan_unit", "estimator", "run_constants"):
        assert content_type in registered_content_types()
        assert content_type not in KNOWN_UNRENDERED_ALLOWLIST
    assert get_renderer("plan_unit") is render_plan_unit
    assert get_renderer("estimator") is render_estimator
    assert get_renderer("run_constants") is render_run_constants


# ---------------------------------------------------------------------------
# AC-2 — the gate→content_type bridge (resolver level).
# ---------------------------------------------------------------------------


def test_bridge_maps_paused_gate_identifiers_to_content_types() -> None:
    """AC-2: G1A (gate string + surface_id) and the two G1.5 surface_ids resolve to
    their SEMANTIC content-type keys."""
    assert resolve_content_type("G1A") == "plan_unit"
    assert resolve_content_type("section_04a_g1a_poll") == "plan_unit"
    assert resolve_content_type("section_04_5_g1_5_estimator") == "estimator"
    assert resolve_content_type("section_04_55_g1_5_run_constants") == "run_constants"


def test_shared_g1_5_gate_string_is_deliberately_unmapped() -> None:
    """AC-2: the bare "G1.5" gate string is SHARED by estimator + run_constants, so it
    is deliberately NOT mapped (mapping it to either would mis-route the other). An
    unmapped gate resolves to ``None`` → the generic fallback (still tables, no raw
    dump). The poll-surface ``surface_id`` is the disambiguating routing key."""
    assert resolve_content_type("G1.5") is None
    assert get_renderer(resolve_content_type("G1.5")) is render_generic_gate_content


def test_bridge_routes_paused_gates_to_bespoke_renderers_not_generic() -> None:
    """AC-2: resolving each paused gate then fetching the renderer yields the BESPOKE
    renderer, not the generic fallback."""
    assert get_renderer(resolve_content_type("G1A")) is render_plan_unit
    assert (
        get_renderer(resolve_content_type("section_04_5_g1_5_estimator"))
        is render_estimator
    )
    assert (
        get_renderer(resolve_content_type("section_04_55_g1_5_run_constants"))
        is render_run_constants
    )
    assert get_renderer(resolve_content_type("G1A")) is not render_generic_gate_content


# ---------------------------------------------------------------------------
# AC-1 — G1A plan-unit ratification table shape.
# ---------------------------------------------------------------------------


def test_plan_unit_table_shape() -> None:
    """AC-1 (names **G1A plan-unit ratification**): the rendered table carries the
    banner and the plan-unit's ratification attributes (unit id / event type / weather
    band / scope verdict / modality / gaps count), not a raw Field|Value dump."""
    content = _load(PLAN_UNIT_FIXTURE)
    out = render_plan_unit(content)

    assert "G1A plan-unit ratification" in out
    assert "| Attribute | Value |" in out
    assert "gagne-event-3" in out
    assert "present-content" in out
    assert "green" in out
    assert "in-scope" in out
    assert "slides" in out
    assert "2 gap(s)" in out
    # NOT the generic fallback.
    assert "| Field | Value |" not in out


def test_plan_unit_dispatch_through_render_gate_content() -> None:
    """AC-1: dispatch via the registry (``content_type='plan_unit'``) yields the
    bespoke table, not the generic Field|Value fallback."""
    content = _load(PLAN_UNIT_FIXTURE)
    out = render_gate_content(content, content_type="plan_unit")
    assert "G1A plan-unit ratification" in out
    assert "| Field | Value |" not in out


def test_plan_unit_accepts_g1_card_body_shape() -> None:
    """AC-5: the renderer tolerates the G1 decision-card ``card`` body shape (PlanUnit
    nested at ``drafted_proposal.plan_unit``), not only the ``display_plan_unit``
    return shape."""
    card_body = _load(PLAN_UNIT_FIXTURE)["decision_card"]
    out = render_plan_unit(card_body)
    assert "G1A plan-unit ratification" in out
    assert "gagne-event-3" in out
    assert "| Field | Value |" not in out


def test_plan_unit_accepts_bare_plan_unit_mapping() -> None:
    """AC-5: a bare PlanUnit mapping handed directly still tables its attributes."""
    bare = _load(PLAN_UNIT_FIXTURE)["plan_unit"]
    out = render_plan_unit(bare)
    assert "G1A plan-unit ratification" in out
    assert "gagne-event-3" in out


# ---------------------------------------------------------------------------
# AC-1 — G1.5 run-budget estimator table shape.
# ---------------------------------------------------------------------------


def test_estimator_table_shape() -> None:
    """AC-1 (names **G1.5 run-budget estimator**): the rendered table carries the
    banner and one row per estimate line item (parent slide count, runtime, feasibility
    — the section_04_5 estimator's ``drafted_proposal`` values)."""
    content = _load(ESTIMATOR_FIXTURE)
    out = render_estimator(content)

    assert "G1.5 run-budget estimator" in out
    assert "| Line item | Value |" in out
    assert "parent_slide_count" in out
    assert "8" in out
    assert "feasibility" in out
    assert "PASS" in out
    assert "5 line item(s)" in out
    # NOT the generic fallback.
    assert "| Field | Value |" not in out


def test_estimator_dispatch_through_render_gate_content() -> None:
    """AC-1: dispatch via the registry (``content_type='estimator'``) yields the
    bespoke table, not the generic Field|Value fallback."""
    content = _load(ESTIMATOR_FIXTURE)
    out = render_gate_content(content, content_type="estimator")
    assert "G1.5 run-budget estimator" in out
    assert "| Field | Value |" not in out


def test_estimator_accepts_bare_g1_card_body() -> None:
    """AC-5: the renderer tolerates the bare estimator G1Card ``card`` body (the
    ``estimator`` sub-map handed directly), not only the display return shape."""
    bare = _load(ESTIMATOR_FIXTURE)["estimator"]
    out = render_estimator(bare)
    assert "G1.5 run-budget estimator" in out
    assert "parent_slide_count" in out
    assert "5 line item(s)" in out


# ---------------------------------------------------------------------------
# AC-1 — G1.5 run-constants lock table shape.
# ---------------------------------------------------------------------------


def test_run_constants_table_shape() -> None:
    """AC-1 (names **G1.5 run-constants lock**): the rendered table carries the banner
    and one row per constant; a nested ``cluster_density`` sub-map is bounded-summarized
    (never raw-dumped)."""
    content = _load(RUN_CONSTANTS_FIXTURE)
    out = render_run_constants(content)

    assert "G1.5 run-constants lock" in out
    assert "| Constant | Value |" in out
    assert "RUN-CONSTANTS-001" in out
    assert "lesson_slug" in out
    assert "agentic-production-platform" in out
    assert "experience_profile" in out
    assert "motion_enabled" in out
    # Nested sub-map summarized, not raw-dumped.
    assert "cluster_density" in out
    assert "5 constant(s)" in out
    # NOT the generic fallback.
    assert "| Field | Value |" not in out


def test_run_constants_dispatch_through_render_gate_content() -> None:
    """AC-1: dispatch via the registry (``content_type='run_constants'``) yields the
    bespoke table, not the generic Field|Value fallback."""
    content = _load(RUN_CONSTANTS_FIXTURE)
    out = render_gate_content(content, content_type="run_constants")
    assert "G1.5 run-constants lock" in out
    assert "| Field | Value |" not in out


def test_run_constants_accepts_bare_constants_mapping() -> None:
    """AC-5: a bare run-constants mapping handed directly still tables one row per
    constant and recovers the id from ``run_id``."""
    bare = _load(RUN_CONSTANTS_FIXTURE)["run_constants"]
    out = render_run_constants(bare)
    assert "G1.5 run-constants lock" in out
    assert "RUN-CONSTANTS-001" in out
    assert "lesson_slug" in out


# ---------------------------------------------------------------------------
# AC-2 (end-to-end) — PAUSED gates route to the bespoke renderers via trial.py.
# ---------------------------------------------------------------------------


def _write_paused_run(
    tmp_path: Path, *, gate: str, card_body: dict[str, Any]
) -> dict[str, Any]:
    """Materialize a minimal paused-at-gate run dir + payload for the given gate."""
    run_dir = tmp_path / "run"
    run_dir.mkdir(parents=True, exist_ok=True)
    (run_dir / f"decision-card-{gate}.json").write_text(
        json.dumps({"card": card_body}, indent=2), encoding="utf-8"
    )
    return {
        "status": "paused-at-gate",
        "trial_id": "aaaaaaaa-bbbb-4ccc-8ddd-eeeeeeeeeeee",
        "paused_gate": gate,
        "operator_id": "operator",
        "run_registry_path": str(run_dir / "run-registry.json"),
    }


def test_paused_g1a_routes_to_bespoke_plan_unit_renderer_via_trial(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """AC-2 (end-to-end): a paused G1A fixture emitted through
    ``trial.py::_emit_gate_surface_if_paused`` reaches the BESPOKE plan-unit renderer
    (its banner appears on stderr), NOT the generic Field|Value fallback."""
    card_body = _load(PLAN_UNIT_FIXTURE)
    payload = _write_paused_run(tmp_path, gate="G1A", card_body=card_body)

    trial._emit_gate_surface_if_paused(payload, runs_root=tmp_path)

    err = capsys.readouterr().err
    assert "G1A plan-unit ratification" in err  # bespoke renderer fired
    assert "gagne-event-3" in err
    assert "| Field | Value |" not in err  # generic fallback did NOT fire


def test_paused_estimator_routes_to_bespoke_renderer_via_trial(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """AC-2 (end-to-end): a paused estimator gate keyed by its section_04_5
    ``surface_id`` (the disambiguator for the shared G1.5 gate) reaches the BESPOKE
    estimator renderer, NOT the generic fallback."""
    card_body = _load(ESTIMATOR_FIXTURE)
    payload = _write_paused_run(
        tmp_path, gate="section_04_5_g1_5_estimator", card_body=card_body
    )

    trial._emit_gate_surface_if_paused(payload, runs_root=tmp_path)

    err = capsys.readouterr().err
    assert "G1.5 run-budget estimator" in err  # bespoke renderer fired
    assert "parent_slide_count" in err
    assert "| Field | Value |" not in err  # generic fallback did NOT fire


def test_paused_run_constants_routes_to_bespoke_renderer_via_trial(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """AC-2 (end-to-end): a paused run-constants gate keyed by its section_04_55
    ``surface_id`` reaches the BESPOKE run-constants renderer, NOT the generic
    fallback."""
    card_body = _load(RUN_CONSTANTS_FIXTURE)
    payload = _write_paused_run(
        tmp_path, gate="section_04_55_g1_5_run_constants", card_body=card_body
    )

    trial._emit_gate_surface_if_paused(payload, runs_root=tmp_path)

    err = capsys.readouterr().err
    assert "G1.5 run-constants lock" in err  # bespoke renderer fired
    assert "lesson_slug" in err
    assert "| Field | Value |" not in err  # generic fallback did NOT fire
