"""Story 43-7 — motion-plan + motion-clip renderers (+ the gate→renderer bridge).

Two content types the operator reviews on the motion band: **G2.5 motion-plan status**
(section_07d — is the deterministic motion plan ready to proceed) and **G2F motion-clip**
(section_07f — is the generated / imported motion clip ready). Both poll-surfaces bind the
shared ``G2CCard`` pre-execution sanity card; the renderers table its real review
attributes (readiness, blocking-issue / ready-node counts, gate focus, verb) rather than a
non-existent motion-detail field (the motion plan is an internal producer→consumer envelope,
not a card field — mirrors 43-6's storyboard_b tabling the G3Card attributes rather than an
imaginary live-URL field). Replay-only against the SYNTHETIC fixtures under
``tests/fixtures/hil_projector/`` (``poll-motion-plan-synthetic.json`` /
``poll-motion-clip-synthetic.json``), each generated by invoking the REAL
``poll_surface.display_*`` function against a constructed ``G2CCard`` (zero live spend).

Proves:

* **AC-1** — two bespoke renderers table each gate's content on its merits (named-attribute
  rows), never the generic ``Field | Value`` dump.
* **AC-2 (the bridge)** — the paused-gate identifiers route through
  ``GATE_TO_CONTENT_TYPE`` to the BESPOKE renderers, both at the resolver level AND
  end-to-end through ``trial.py::_emit_gate_surface_if_paused``. ``motion_plan`` is keyed by
  its ``surface_id`` ONLY (its gate_code "G2M" is claimed by ``variant_ab``, its fold-target
  "G2C" is shared, and bare "G2.5" belongs to the cluster-coherence node); ``motion_clip`` is
  keyed by the unambiguous "G2F" gate_code + its ``surface_id`` (the shared "G3" fold-target
  is deliberately unmapped — 43-6 already pinned it).
* **AC-4** — both moved allowlist → registry (disjoint invariant holds).
* **AC-5** — the renderers stay stdlib-pure and tolerate BOTH the ``display_*`` return shape
  AND a bare ``G2CCard`` card body.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest

import app.marcus.cli.trial as trial
from app.marcus.cli.hil_tabular_projector import (
    KNOWN_UNRENDERED_ALLOWLIST,
    get_renderer,
    registered_content_types,
    render_gate_content,
    render_generic_gate_content,
    render_motion_clip,
    render_motion_plan,
    resolve_content_type,
)

FIXTURES = Path(__file__).resolve().parents[3] / "tests" / "fixtures" / "hil_projector"
MOTION_PLAN_FIXTURE = FIXTURES / "poll-motion-plan-synthetic.json"
MOTION_CLIP_FIXTURE = FIXTURES / "poll-motion-clip-synthetic.json"


def _load(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


# ---------------------------------------------------------------------------
# AC-4 — allowlist → registry moves.
# ---------------------------------------------------------------------------


def test_renderers_are_registered_and_off_the_allowlist() -> None:
    """AC-4: ``motion_plan`` / ``motion_clip`` dispatch to bespoke renderers and have LEFT
    the shrink-only allowlist (disjoint invariant requires the deletion)."""
    for content_type in ("motion_plan", "motion_clip"):
        assert content_type in registered_content_types()
        assert content_type not in KNOWN_UNRENDERED_ALLOWLIST
    assert get_renderer("motion_plan") is render_motion_plan
    assert get_renderer("motion_clip") is render_motion_clip


# ---------------------------------------------------------------------------
# AC-2 — the gate→content_type bridge (resolver level).
# ---------------------------------------------------------------------------


def test_bridge_maps_paused_gate_identifiers_to_content_types() -> None:
    """AC-2: the motion surface_ids (+ the unambiguous "G2F" gate_code) resolve to their
    SEMANTIC content-type keys."""
    assert resolve_content_type("section_07d_g2_5_motion_plan_polling") == "motion_plan"
    assert resolve_content_type("G2F") == "motion_clip"
    assert resolve_content_type("section_07f_g2f_motion_gate") == "motion_clip"


def test_shared_and_claimed_gate_strings_are_deliberately_unmapped() -> None:
    """AC-2: no bare gate string is mapped for motion_plan — "G2M" is claimed by
    ``variant_ab`` (NOT motion_plan), "G2.5" belongs to the cluster-coherence node, and the
    shared fold-targets "G2C" / "G3" are deliberately unmapped (mapping any would mis-route).
    An unmapped/foreign gate resolves to its OWN content type or ``None`` → the generic
    fallback still tables (no raw dump)."""
    # "G2M" is variant_ab's key — it must NOT resolve to motion_plan.
    assert resolve_content_type("G2M") == "variant_ab"
    # The two shared fold-targets and the foreign cluster-coherence "G2.5" are unmapped.
    for gate in ("G2C", "G3", "G2.5"):
        assert resolve_content_type(gate) is None
        assert get_renderer(resolve_content_type(gate)) is render_generic_gate_content


def test_bridge_routes_paused_gates_to_bespoke_renderers_not_generic() -> None:
    """AC-2: resolving each paused gate then fetching the renderer yields the BESPOKE
    renderer, not the generic fallback."""
    assert (
        get_renderer(resolve_content_type("section_07d_g2_5_motion_plan_polling"))
        is render_motion_plan
    )
    assert get_renderer(resolve_content_type("G2F")) is render_motion_clip
    assert get_renderer(resolve_content_type("G2F")) is not render_generic_gate_content


# ---------------------------------------------------------------------------
# AC-1 — G2.5 motion-plan status table shape.
# ---------------------------------------------------------------------------


def test_motion_plan_table_shape() -> None:
    """AC-1 (names **G2.5 motion-plan status**): the rendered table carries the banner and
    the G2C review attributes as named rows, not a raw Field|Value dump."""
    content = _load(MOTION_PLAN_FIXTURE)
    out = render_motion_plan(content)

    assert "G2.5 motion-plan status" in out
    assert "| Attribute | Value |" in out
    assert "11111111-1111-4111-8111-111111111111" in out  # motion_plan_id
    assert "status completed" in out
    assert "readiness" in out
    assert "3 node(s)" in out  # ready_nodes count
    assert "0 issue(s)" in out  # blocking_issues count
    # NOT the generic fallback.
    assert "| Field | Value |" not in out


def test_motion_plan_dispatch_through_render_gate_content() -> None:
    """AC-1: dispatch via the registry (``content_type='motion_plan'``) yields the bespoke
    table, not the generic Field|Value fallback."""
    content = _load(MOTION_PLAN_FIXTURE)
    out = render_gate_content(content, content_type="motion_plan")
    assert "G2.5 motion-plan status" in out
    assert "| Field | Value |" not in out


def test_motion_plan_accepts_bare_g2c_card_body() -> None:
    """AC-5: the renderer tolerates the bare ``G2CCard`` card body (the mapping under
    ``decision_card`` handed directly) — proving it tables the SAME model that flows at the
    real paused motion gate (folded into G2C). The top-level ``motion_plan_status`` is absent
    on the bare card, so the status falls back to the readiness-derived value."""
    bare = _load(MOTION_PLAN_FIXTURE)["decision_card"]
    out = render_motion_plan(bare)
    assert "G2.5 motion-plan status" in out
    assert "11111111-1111-4111-8111-111111111111" in out
    assert "status completed" in out  # derived from readiness_status == "ready"


# ---------------------------------------------------------------------------
# AC-1 — G2F motion-clip table shape.
# ---------------------------------------------------------------------------


def test_motion_clip_table_shape() -> None:
    """AC-1 (names **G2F motion-clip**): the rendered table carries the banner and the G2C
    review attributes as named rows, not a raw Field|Value dump."""
    content = _load(MOTION_CLIP_FIXTURE)
    out = render_motion_clip(content)

    assert "G2F motion-clip" in out
    assert "| Attribute | Value |" in out
    assert "22222222-2222-4222-8222-222222222222" in out  # motion_clip_id
    assert "readiness ready" in out
    assert "2 node(s)" in out  # ready_nodes count
    assert "0 issue(s)" in out  # blocking_issues count
    # NOT the generic fallback.
    assert "| Field | Value |" not in out


def test_motion_clip_dispatch_through_render_gate_content() -> None:
    """AC-1: dispatch via the registry (``content_type='motion_clip'``) yields the bespoke
    table, not the generic Field|Value fallback."""
    content = _load(MOTION_CLIP_FIXTURE)
    out = render_gate_content(content, content_type="motion_clip")
    assert "G2F motion-clip" in out
    assert "| Field | Value |" not in out


def test_motion_clip_accepts_bare_g2c_card_body() -> None:
    """AC-5: the renderer tolerates the bare ``G2CCard`` card body (the mapping under
    ``decision_card`` handed directly) — proving it tables the SAME model the section_07f
    poll-surface binds."""
    bare = _load(MOTION_CLIP_FIXTURE)["decision_card"]
    out = render_motion_clip(bare)
    assert "G2F motion-clip" in out
    assert "22222222-2222-4222-8222-222222222222" in out
    assert "readiness ready" in out


# ---------------------------------------------------------------------------
# AC-2 (end-to-end) — PAUSED gates route to the bespoke renderers via trial.py.
# ---------------------------------------------------------------------------


def _write_paused_run(
    tmp_path: Path, *, gate: str, card_body: dict[str, Any]
) -> dict[str, Any]:
    """Materialize a minimal paused-at-gate run dir + payload for the given gate."""
    run_dir = tmp_path / "run"
    run_dir.mkdir(parents=True, exist_ok=True)
    (run_dir / f"decision-card-{gate}.json").write_text(
        json.dumps({"card": card_body}, indent=2), encoding="utf-8"
    )
    return {
        "status": "paused-at-gate",
        "trial_id": "aaaaaaaa-bbbb-4ccc-8ddd-eeeeeeeeeeee",
        "paused_gate": gate,
        "operator_id": "operator",
        "run_registry_path": str(run_dir / "run-registry.json"),
    }


def test_paused_motion_plan_routes_to_bespoke_renderer_via_trial(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """AC-2 (end-to-end): a paused motion-plan gate keyed by its section_07d ``surface_id``
    (the sole routing key; the shared "G2C" fold-target is deliberately unmapped) reaches the
    BESPOKE motion-plan renderer, NOT the generic fallback."""
    card_body = _load(MOTION_PLAN_FIXTURE)
    payload = _write_paused_run(
        tmp_path, gate="section_07d_g2_5_motion_plan_polling", card_body=card_body
    )

    trial._emit_gate_surface_if_paused(payload, runs_root=tmp_path)

    err = capsys.readouterr().err
    assert "G2.5 motion-plan status" in err  # bespoke renderer fired
    assert "11111111-1111-4111-8111-111111111111" in err
    assert "| Field | Value |" not in err  # generic fallback did NOT fire


def test_paused_motion_clip_routes_to_bespoke_renderer_via_trial(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """AC-2 (end-to-end): a paused G2F gate (the unambiguous gate_code; the shared "G3"
    fold-target is deliberately unmapped) reaches the BESPOKE motion-clip renderer, NOT the
    generic fallback."""
    card_body = _load(MOTION_CLIP_FIXTURE)
    payload = _write_paused_run(tmp_path, gate="G2F", card_body=card_body)

    trial._emit_gate_surface_if_paused(payload, runs_root=tmp_path)

    err = capsys.readouterr().err
    assert "G2F motion-clip" in err  # bespoke renderer fired
    assert "22222222-2222-4222-8222-222222222222" in err
    assert "| Field | Value |" not in err  # generic fallback did NOT fire
