"""Story 43-6 — build-target list renderers (+ the gate→renderer bridge).

Three content types the operator reviews mid-deck: **06B literal-visual build
targets**, **07C storyboard build targets**, and **G3B storyboard / live-URL
review** (the G3 card). Replay-only against the SYNTHETIC fixtures under
``tests/fixtures/hil_projector/`` (``poll-literal-visual-synthetic.json`` /
``poll-storyboard-targets-synthetic.json`` / ``poll-storyboard-b-synthetic.json``),
each generated by invoking the REAL ``poll_surface.display_*`` function against a
constructed payload / model (zero live spend).

Proves:

* **AC-1** — three bespoke renderers table each gate's content on its merits, never
  the generic ``Field | Value`` dump.
* **AC-2 (the bridge)** — the paused-gate identifiers route through
  ``GATE_TO_CONTENT_TYPE`` to the BESPOKE renderers, both at the resolver level AND
  end-to-end through ``trial.py::_emit_gate_surface_if_paused``. The 06B/07C/G3B
  content types are keyed by their poll-surface ``surface_id`` (06B is a non-gate
  node; 07C's gate_code "G2C" and G3B's fold-target "G3" are SHARED gate strings and
  deliberately unmapped — mirrors 43-5's G1.5 split). The unambiguous "G3B"
  gate_code additionally routes to ``storyboard_b``.
* **AC-4** — all three moved allowlist → registry (disjoint invariant holds).
* **AC-5** — the renderers stay stdlib-pure and tolerate BOTH the ``display_*``
  return shape AND a bare payload / card body.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest

import app.marcus.cli.trial as trial
from app.marcus.cli.hil_tabular_projector import (
    KNOWN_UNRENDERED_ALLOWLIST,
    get_renderer,
    registered_content_types,
    render_gate_content,
    render_generic_gate_content,
    render_literal_visual,
    render_storyboard_b,
    render_storyboard_targets,
    resolve_content_type,
)

FIXTURES = Path(__file__).resolve().parents[3] / "tests" / "fixtures" / "hil_projector"
LITERAL_VISUAL_FIXTURE = FIXTURES / "poll-literal-visual-synthetic.json"
STORYBOARD_TARGETS_FIXTURE = FIXTURES / "poll-storyboard-targets-synthetic.json"
STORYBOARD_B_FIXTURE = FIXTURES / "poll-storyboard-b-synthetic.json"


def _load(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


# ---------------------------------------------------------------------------
# AC-4 — allowlist → registry moves.
# ---------------------------------------------------------------------------


def test_renderers_are_registered_and_off_the_allowlist() -> None:
    """AC-4: ``literal_visual`` / ``storyboard_targets`` / ``storyboard_b`` dispatch to
    bespoke renderers and have LEFT the shrink-only allowlist (disjoint invariant
    requires the deletion)."""
    for content_type in ("literal_visual", "storyboard_targets", "storyboard_b"):
        assert content_type in registered_content_types()
        assert content_type not in KNOWN_UNRENDERED_ALLOWLIST
    assert get_renderer("literal_visual") is render_literal_visual
    assert get_renderer("storyboard_targets") is render_storyboard_targets
    assert get_renderer("storyboard_b") is render_storyboard_b


# ---------------------------------------------------------------------------
# AC-2 — the gate→content_type bridge (resolver level).
# ---------------------------------------------------------------------------


def test_bridge_maps_paused_gate_identifiers_to_content_types() -> None:
    """AC-2: the three surface_ids (+ the unambiguous "G3B" gate_code) resolve to their
    SEMANTIC content-type keys."""
    assert resolve_content_type("section_06b_literal_visual_build") == "literal_visual"
    assert resolve_content_type("section_07c_storyboard_build") == "storyboard_targets"
    assert resolve_content_type("G3B") == "storyboard_b"
    assert resolve_content_type("section_08b_g3b_poll") == "storyboard_b"


def test_shared_gate_strings_are_deliberately_unmapped() -> None:
    """AC-2: "G2C" (shared by 07C storyboard + G2B/G2M fold-ins) and "G3" (shared by G3B
    storyboard-B + G2F motion-clip fold-ins) are SHARED fold-target gate strings, so they
    are deliberately NOT mapped (mapping either would mis-route). An unmapped gate resolves
    to ``None`` → the generic fallback (still tables, no raw dump). The poll-surface
    ``surface_id`` is the disambiguating routing key (mirrors 43-5's shared-G1.5 split)."""
    assert resolve_content_type("G2C") is None
    assert resolve_content_type("G3") is None
    assert get_renderer(resolve_content_type("G2C")) is render_generic_gate_content
    assert get_renderer(resolve_content_type("G3")) is render_generic_gate_content


def test_bridge_routes_paused_gates_to_bespoke_renderers_not_generic() -> None:
    """AC-2: resolving each paused gate then fetching the renderer yields the BESPOKE
    renderer, not the generic fallback."""
    assert (
        get_renderer(resolve_content_type("section_06b_literal_visual_build"))
        is render_literal_visual
    )
    assert (
        get_renderer(resolve_content_type("section_07c_storyboard_build"))
        is render_storyboard_targets
    )
    assert get_renderer(resolve_content_type("G3B")) is render_storyboard_b
    assert get_renderer(resolve_content_type("G3B")) is not render_generic_gate_content


# ---------------------------------------------------------------------------
# AC-1 — 06B literal-visual build targets table shape.
# ---------------------------------------------------------------------------


def test_literal_visual_table_shape() -> None:
    """AC-1 (names **06B literal-visual build targets**): the rendered table carries the
    banner and one row per slide target (slide index / visual kind / specification /
    caption), not a raw Field|Value dump."""
    content = _load(LITERAL_VISUAL_FIXTURE)
    out = render_literal_visual(content)

    assert "06B literal-visual build targets" in out
    assert "| # | slide | Visual kind | Specification | Caption |" in out
    assert "flowchart" in out
    assert "Enrollment funnel" in out
    assert "bar-chart" in out
    assert "3 target(s)" in out
    assert "unit-06b-synthetic" in out
    # NOT the generic fallback.
    assert "| Field | Value |" not in out


def test_literal_visual_dispatch_through_render_gate_content() -> None:
    """AC-1: dispatch via the registry (``content_type='literal_visual'``) yields the
    bespoke table, not the generic Field|Value fallback."""
    content = _load(LITERAL_VISUAL_FIXTURE)
    out = render_gate_content(content, content_type="literal_visual")
    assert "06B literal-visual build targets" in out
    assert "| Field | Value |" not in out


def test_literal_visual_accepts_bare_build_payload() -> None:
    """AC-5: the renderer tolerates a bare build payload (rows under
    ``slide_specifications``), not only the ``display_*`` return shape."""
    bare = _load(LITERAL_VISUAL_FIXTURE)["source_payload"]
    out = render_literal_visual(bare)
    assert "06B literal-visual build targets" in out
    assert "flowchart" in out
    assert "3 target(s)" in out


# ---------------------------------------------------------------------------
# AC-1 — 07C storyboard build targets table shape.
# ---------------------------------------------------------------------------


def test_storyboard_targets_table_shape() -> None:
    """AC-1 (names **07C storyboard build targets**): the rendered table carries the
    banner and one row per storyboard slide (slide index / title / body / caption)."""
    content = _load(STORYBOARD_TARGETS_FIXTURE)
    out = render_storyboard_targets(content)

    assert "07C storyboard build targets" in out
    assert "| # | slide | Title | Body | Caption |" in out
    assert "Opening" in out
    assert "Core concept" in out
    assert "Material partition" in out
    assert "3 slide(s)" in out
    assert "unit-07c-synthetic" in out
    # NOT the generic fallback.
    assert "| Field | Value |" not in out


def test_storyboard_targets_dispatch_through_render_gate_content() -> None:
    """AC-1: dispatch via the registry (``content_type='storyboard_targets'``) yields the
    bespoke table, not the generic Field|Value fallback."""
    content = _load(STORYBOARD_TARGETS_FIXTURE)
    out = render_gate_content(content, content_type="storyboard_targets")
    assert "07C storyboard build targets" in out
    assert "| Field | Value |" not in out


def test_storyboard_targets_accepts_bare_payload() -> None:
    """AC-5: the renderer tolerates a bare payload (rows under ``slides``), not only the
    ``display_*`` return shape."""
    bare = _load(STORYBOARD_TARGETS_FIXTURE)["source_payload"]
    out = render_storyboard_targets(bare)
    assert "07C storyboard build targets" in out
    assert "Opening" in out
    assert "3 slide(s)" in out


# ---------------------------------------------------------------------------
# AC-1 — G3B storyboard / live-URL review table shape.
# ---------------------------------------------------------------------------


def test_storyboard_b_table_shape() -> None:
    """AC-1 (names **G3B storyboard / live-URL review**): the rendered table carries the
    banner and the G3 card's review attributes (storyboard id / gate focus / progress /
    active node / pending count / verb / operator prompt), not a raw Field|Value dump."""
    content = _load(STORYBOARD_B_FIXTURE)
    out = render_storyboard_b(content)

    assert "G3B storyboard / live-URL review" in out
    assert "| Attribute | Value |" in out
    assert "55555555-5555-4555-8555-555555555555" in out
    assert "storyboard-b-live-url-review" in out
    assert "62.5%" in out
    assert "approve" in out
    assert "2 pending node(s)" in out
    assert "Review Storyboard B" in out
    # NOT the generic fallback.
    assert "| Field | Value |" not in out


def test_storyboard_b_dispatch_through_render_gate_content() -> None:
    """AC-1: dispatch via the registry (``content_type='storyboard_b'``) yields the
    bespoke table, not the generic Field|Value fallback."""
    content = _load(STORYBOARD_B_FIXTURE)
    out = render_gate_content(content, content_type="storyboard_b")
    assert "G3B storyboard / live-URL review" in out
    assert "| Field | Value |" not in out


def test_storyboard_b_accepts_bare_g3_card_body() -> None:
    """AC-5: the renderer tolerates the bare ``G3Card`` ``card`` body (the mapping under
    ``decision_card`` handed directly), not only the ``display_storyboard_b`` return
    shape — proving it tables the SAME model that flows at the real paused G3."""
    bare = _load(STORYBOARD_B_FIXTURE)["decision_card"]
    out = render_storyboard_b(bare)
    assert "G3B storyboard / live-URL review" in out
    assert "storyboard-b-live-url-review" in out
    assert "approve" in out


# ---------------------------------------------------------------------------
# AC-2 (end-to-end) — PAUSED gates route to the bespoke renderers via trial.py.
# ---------------------------------------------------------------------------


def _write_paused_run(
    tmp_path: Path, *, gate: str, card_body: dict[str, Any]
) -> dict[str, Any]:
    """Materialize a minimal paused-at-gate run dir + payload for the given gate."""
    run_dir = tmp_path / "run"
    run_dir.mkdir(parents=True, exist_ok=True)
    (run_dir / f"decision-card-{gate}.json").write_text(
        json.dumps({"card": card_body}, indent=2), encoding="utf-8"
    )
    return {
        "status": "paused-at-gate",
        "trial_id": "aaaaaaaa-bbbb-4ccc-8ddd-eeeeeeeeeeee",
        "paused_gate": gate,
        "operator_id": "operator",
        "run_registry_path": str(run_dir / "run-registry.json"),
    }


def test_paused_literal_visual_routes_to_bespoke_renderer_via_trial(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """AC-2 (end-to-end): a paused 06B gate keyed by its section_06b ``surface_id``
    (06B is a non-gate node, so the surface_id is the only routing key) reaches the
    BESPOKE literal-visual renderer, NOT the generic fallback."""
    card_body = _load(LITERAL_VISUAL_FIXTURE)
    payload = _write_paused_run(
        tmp_path, gate="section_06b_literal_visual_build", card_body=card_body
    )

    trial._emit_gate_surface_if_paused(payload, runs_root=tmp_path)

    err = capsys.readouterr().err
    assert "06B literal-visual build targets" in err  # bespoke renderer fired
    assert "flowchart" in err
    assert "| Field | Value |" not in err  # generic fallback did NOT fire


def test_paused_storyboard_targets_routes_to_bespoke_renderer_via_trial(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """AC-2 (end-to-end): a paused 07C gate keyed by its section_07c ``surface_id`` (the
    disambiguator for the shared G2C fold-target) reaches the BESPOKE storyboard-targets
    renderer, NOT the generic fallback."""
    card_body = _load(STORYBOARD_TARGETS_FIXTURE)
    payload = _write_paused_run(
        tmp_path, gate="section_07c_storyboard_build", card_body=card_body
    )

    trial._emit_gate_surface_if_paused(payload, runs_root=tmp_path)

    err = capsys.readouterr().err
    assert "07C storyboard build targets" in err  # bespoke renderer fired
    assert "Opening" in err
    assert "| Field | Value |" not in err  # generic fallback did NOT fire


def test_paused_storyboard_b_routes_to_bespoke_renderer_via_trial(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """AC-2 (end-to-end): a paused G3B gate (the unambiguous gate_code; the shared "G3"
    fold-target is deliberately unmapped) reaches the BESPOKE storyboard-b renderer, NOT
    the generic fallback."""
    card_body = _load(STORYBOARD_B_FIXTURE)
    payload = _write_paused_run(tmp_path, gate="G3B", card_body=card_body)

    trial._emit_gate_surface_if_paused(payload, runs_root=tmp_path)

    err = capsys.readouterr().err
    assert "G3B storyboard / live-URL review" in err  # bespoke renderer fired
    assert "storyboard-b-live-url-review" in err
    assert "| Field | Value |" not in err  # generic fallback did NOT fire
