"""Story 43-8 — input-package + final-handoff renderers (+ the gate→renderer bridge).

Two content types the operator reviews at the tail of a run: **G4B input-package
preview** (the ElevenLabs audio-synthesis handoff package) and **G5 final handoff**
(the composited-bundle delivery). Replay-only against the SYNTHETIC fixtures under
``tests/fixtures/hil_projector/`` (``poll-input-package-synthetic.json`` /
``poll-final-handoff-synthetic.json``), each generated by invoking the REAL
``poll_surface.display_*`` function against a constructed ``G4Card`` / ``G5Card``
model (zero live spend).

Proves:

* **AC-1** — two bespoke renderers table each gate's content on its merits (one row
  per artifact path), never the generic ``Field | Value`` dump.
* **AC-2 (the bridge)** — the paused-gate identifiers route through
  ``GATE_TO_CONTENT_TYPE`` to the BESPOKE renderers, both at the resolver level AND
  end-to-end through ``trial.py::_emit_gate_surface_if_paused``. Nodes 11B-gate
  ("G4B") and 13 ("G5") BOTH fold into the shared "G4" pause (as does the G4 closeout
  itself), so "G4" is deliberately unmapped; the unambiguous "G4B"/"G5" gate_codes +
  the poll-surface ``surface_id``s are the routing keys (mirrors 43-5/43-6 shared-fold
  discipline).
* **AC-4** — both moved allowlist → registry (disjoint invariant holds).
* **AC-5** — the renderers stay stdlib-pure and tolerate BOTH the ``display_*`` return
  shape AND a bare payload / card body.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest

import app.marcus.cli.trial as trial
from app.marcus.cli.hil_tabular_projector import (
    KNOWN_UNRENDERED_ALLOWLIST,
    get_renderer,
    registered_content_types,
    render_final_handoff,
    render_gate_content,
    render_generic_gate_content,
    render_input_package,
    resolve_content_type,
)

FIXTURES = Path(__file__).resolve().parents[3] / "tests" / "fixtures" / "hil_projector"
INPUT_PACKAGE_FIXTURE = FIXTURES / "poll-input-package-synthetic.json"
FINAL_HANDOFF_FIXTURE = FIXTURES / "poll-final-handoff-synthetic.json"


def _load(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


# ---------------------------------------------------------------------------
# AC-4 — allowlist → registry moves.
# ---------------------------------------------------------------------------


def test_renderers_are_registered_and_off_the_allowlist() -> None:
    """AC-4: ``input_package`` / ``final_handoff`` dispatch to bespoke renderers and
    have LEFT the shrink-only allowlist (disjoint invariant requires the deletion)."""
    for content_type in ("input_package", "final_handoff"):
        assert content_type in registered_content_types()
        assert content_type not in KNOWN_UNRENDERED_ALLOWLIST
    assert get_renderer("input_package") is render_input_package
    assert get_renderer("final_handoff") is render_final_handoff


# ---------------------------------------------------------------------------
# AC-2 — the gate→content_type bridge (resolver level).
# ---------------------------------------------------------------------------


def test_bridge_maps_paused_gate_identifiers_to_content_types() -> None:
    """AC-2: the two surface_ids (+ the unambiguous "G4B"/"G5" gate_codes) resolve to
    their SEMANTIC content-type keys."""
    assert resolve_content_type("G4B") == "input_package"
    assert resolve_content_type("section_11b_g4b_input_package") == "input_package"
    assert resolve_content_type("G5") == "final_handoff"
    assert resolve_content_type("section_15_g5_final_handoff") == "final_handoff"


def test_shared_g4_gate_string_is_deliberately_unmapped() -> None:
    """AC-2: "G4" is SHARED by three surfaces — the G4 fidelity closeout itself, G4B
    input-package (node 11B-gate ``fold_with: G4``) and G5 final-handoff (node 13
    ``fold_with: G4``) — so it is deliberately NOT mapped (mapping it would mis-route).
    An unmapped gate resolves to ``None`` → the generic fallback (still tables, no raw
    dump). The poll-surface ``surface_id`` / unambiguous gate_code are the routing keys
    (mirrors 43-5's shared-G1.5 and 43-6's shared-G3 splits)."""
    assert resolve_content_type("G4") is None
    assert get_renderer(resolve_content_type("G4")) is render_generic_gate_content


def test_bridge_routes_paused_gates_to_bespoke_renderers_not_generic() -> None:
    """AC-2: resolving each paused gate then fetching the renderer yields the BESPOKE
    renderer, not the generic fallback."""
    assert get_renderer(resolve_content_type("G4B")) is render_input_package
    assert (
        get_renderer(resolve_content_type("section_11b_g4b_input_package"))
        is render_input_package
    )
    assert get_renderer(resolve_content_type("G5")) is render_final_handoff
    assert get_renderer(resolve_content_type("G5")) is not render_generic_gate_content


# ---------------------------------------------------------------------------
# AC-1 — G4B input-package preview table shape.
# ---------------------------------------------------------------------------


def test_input_package_table_shape() -> None:
    """AC-1 (names **G4B input-package preview**): the rendered table carries the banner
    and one row per artifact path, plus final status + outcome summary, not a raw
    Field|Value dump."""
    content = _load(INPUT_PACKAGE_FIXTURE)
    out = render_input_package(content)

    assert "G4B input-package preview" in out
    assert "| # | Artifact path |" in out
    assert "decision-card-G0E.json" in out
    assert "run_summary.yaml" in out
    assert "5 artifact(s)" in out
    assert "status completed" in out
    assert "Input package assembled" in out  # outcome summary footer
    # NOT the generic fallback.
    assert "| Field | Value |" not in out


def test_input_package_dispatch_through_render_gate_content() -> None:
    """AC-1: dispatch via the registry (``content_type='input_package'``) yields the
    bespoke table, not the generic Field|Value fallback."""
    content = _load(INPUT_PACKAGE_FIXTURE)
    out = render_gate_content(content, content_type="input_package")
    assert "G4B input-package preview" in out
    assert "| Field | Value |" not in out


def test_input_package_accepts_bare_payload() -> None:
    """AC-5: the renderer tolerates the bare ``input_package_payload`` sub-map handed
    directly, not only the ``display_input_package`` return shape."""
    bare = _load(INPUT_PACKAGE_FIXTURE)["input_package_payload"]
    out = render_input_package(bare)
    assert "G4B input-package preview" in out
    assert "decision-card-G0E.json" in out
    assert "5 artifact(s)" in out


def test_input_package_accepts_bare_g4_card_body() -> None:
    """AC-5: the renderer tolerates the bare ``G4Card`` ``card`` body (the mapping under
    ``decision_card`` handed directly) — proving it tables the SAME model that flows at
    the real paused G4 (folded input-package review)."""
    bare = _load(INPUT_PACKAGE_FIXTURE)["decision_card"]
    out = render_input_package(bare)
    assert "G4B input-package preview" in out
    assert "run_summary.yaml" in out
    assert "status completed" in out


# ---------------------------------------------------------------------------
# AC-1 — G5 final-handoff table shape.
# ---------------------------------------------------------------------------


def test_final_handoff_table_shape() -> None:
    """AC-1 (names **G5 final handoff**): the rendered table carries the banner and one
    row per handoff artifact, plus the bundle run + handoff summary, not a raw
    Field|Value dump."""
    content = _load(FINAL_HANDOFF_FIXTURE)
    out = render_final_handoff(content)

    assert "G5 final handoff" in out
    assert "| # | Handoff artifact |" in out
    assert "final-video.mp4" in out
    assert "workbook.docx" in out
    assert "4 artifact(s)" in out
    assert "88888888-8888-4888-8888-888888888888" in out  # bundle_run_id
    assert "Final operator handoff bundle" in out  # handoff summary footer
    # NOT the generic fallback.
    assert "| Field | Value |" not in out


def test_final_handoff_dispatch_through_render_gate_content() -> None:
    """AC-1: dispatch via the registry (``content_type='final_handoff'``) yields the
    bespoke table, not the generic Field|Value fallback."""
    content = _load(FINAL_HANDOFF_FIXTURE)
    out = render_gate_content(content, content_type="final_handoff")
    assert "G5 final handoff" in out
    assert "| Field | Value |" not in out


def test_final_handoff_accepts_bare_payload() -> None:
    """AC-5: the renderer tolerates the bare ``final_handoff_payload`` sub-map handed
    directly, not only the ``display_final_handoff`` return shape."""
    bare = _load(FINAL_HANDOFF_FIXTURE)["final_handoff_payload"]
    out = render_final_handoff(bare)
    assert "G5 final handoff" in out
    assert "final-video.mp4" in out
    assert "4 artifact(s)" in out


def test_final_handoff_accepts_bare_g5_card_body() -> None:
    """AC-5: the renderer tolerates the bare ``G5Card`` ``card`` body (the mapping under
    ``decision_card`` handed directly) — proving it tables the SAME model the section_15
    poll-surface binds."""
    bare = _load(FINAL_HANDOFF_FIXTURE)["decision_card"]
    out = render_final_handoff(bare)
    assert "G5 final handoff" in out
    assert "workbook.docx" in out


# ---------------------------------------------------------------------------
# AC-2 (end-to-end) — PAUSED gates route to the bespoke renderers via trial.py.
# ---------------------------------------------------------------------------


def _write_paused_run(
    tmp_path: Path, *, gate: str, card_body: dict[str, Any]
) -> dict[str, Any]:
    """Materialize a minimal paused-at-gate run dir + payload for the given gate."""
    run_dir = tmp_path / "run"
    run_dir.mkdir(parents=True, exist_ok=True)
    (run_dir / f"decision-card-{gate}.json").write_text(
        json.dumps({"card": card_body}, indent=2), encoding="utf-8"
    )
    return {
        "status": "paused-at-gate",
        "trial_id": "aaaaaaaa-bbbb-4ccc-8ddd-eeeeeeeeeeee",
        "paused_gate": gate,
        "operator_id": "operator",
        "run_registry_path": str(run_dir / "run-registry.json"),
    }


def test_paused_input_package_routes_to_bespoke_renderer_via_trial(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """AC-2 (end-to-end): a paused G4B gate (the unambiguous gate_code; the shared "G4"
    fold-target is deliberately unmapped) reaches the BESPOKE input-package renderer,
    NOT the generic fallback."""
    card_body = _load(INPUT_PACKAGE_FIXTURE)
    payload = _write_paused_run(tmp_path, gate="G4B", card_body=card_body)

    trial._emit_gate_surface_if_paused(payload, runs_root=tmp_path)

    err = capsys.readouterr().err
    assert "G4B input-package preview" in err  # bespoke renderer fired
    assert "decision-card-G0E.json" in err
    assert "| Field | Value |" not in err  # generic fallback did NOT fire


def test_paused_final_handoff_routes_to_bespoke_renderer_via_trial(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """AC-2 (end-to-end): a paused G5 gate keyed by its section_15 ``surface_id`` reaches
    the BESPOKE final-handoff renderer, NOT the generic fallback."""
    card_body = _load(FINAL_HANDOFF_FIXTURE)
    payload = _write_paused_run(
        tmp_path, gate="section_15_g5_final_handoff", card_body=card_body
    )

    trial._emit_gate_surface_if_paused(payload, runs_root=tmp_path)

    err = capsys.readouterr().err
    assert "G5 final handoff" in err  # bespoke renderer fired
    assert "final-video.mp4" in err
    assert "| Field | Value |" not in err  # generic fallback did NOT fire
