from __future__ import annotations

import ast
from pathlib import Path

from skills.bmad_create_specialist.scripts import generate
from tests.specialists.generator.conftest import TEMP_PYPROJECT
from tests.specialists.generator.conftest import make_request as make_request
from tests.specialists.generator.conftest import temp_repo_root as temp_repo_root


def _read_pyproject(repo_root: Path) -> str:
    return (repo_root / "pyproject.toml").read_text(encoding="utf-8")


def _c3_ignore_imports(pyproject_text: str) -> list[str]:
    marker = "ignore_imports = ["
    start = pyproject_text.index(marker) + len(marker)
    end = pyproject_text.index("]", start)
    body = pyproject_text[start:end]
    values: list[str] = []
    for line in body.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        line = line.split("#", 1)[0].strip().rstrip(",")
        if line:
            values.append(ast.literal_eval(line))
    return values


def test_temp_pyproject_baseline_matches_fixture(temp_repo_root: Path) -> None:
    """Pre-emit baseline matches TEMP_PYPROJECT fixture (drift-tolerant; Slab 3.3
    grew the baseline from 5 to 7 entries when gate-bridge ignore_imports landed)."""
    pyproject = _read_pyproject(temp_repo_root)
    actual = _c3_ignore_imports(pyproject)
    baseline = _c3_ignore_imports(TEMP_PYPROJECT)
    assert len(actual) == len(baseline)
    assert set(actual) == set(baseline)


def test_quinn_r_dispatch_wrapper_modules_exist() -> None:
    from app.specialists.quinn_r.quality_control_dispatch import run_precomposition_validators
    from app.specialists.quinn_r.sensory_bridges_dispatch import dispatch_to_sensory_bridges

    assert callable(run_precomposition_validators)
    assert callable(dispatch_to_sensory_bridges)


def test_post_emit_temp_pyproject_has_quinn_r_row_and_no_duplicate(
    temp_repo_root: Path, make_request
) -> None:
    quinn_skill = temp_repo_root / "skills" / "bmad-agent-quality-reviewer"
    quinn_skill.mkdir(parents=True, exist_ok=True)
    (quinn_skill / "SKILL.md").write_text("# quinn skill", encoding="utf-8")

    generate.generate_specialist(
        make_request(
            name="quinn_r",
            mcp_tool="none",
            expertise_tier="L4-quality-review",
            from_skill=quinn_skill,
            repo_root=temp_repo_root,
            force=True,
        )
    )
    pyproject = _read_pyproject(temp_repo_root)
    target = "app.specialists.quinn_r.graph -> app.gates.resume_api"
    rows = _c3_ignore_imports(pyproject)
    assert target in rows
    assert rows.count(target) == 1
    assert "# generated by bmad-create-specialist for quinn_r" in pyproject
