"""Course-source substrate models and deterministic manifest scanning."""

from app.marcus.course_source.asset_records import (
    ASSET_KIND_RECONCILIATION,
    SCHEMA_VERSION,
    AssetKind,
    AssetRecordStatus,
    AssetReview,
    AssetSourceRef,
    CanonicalAssetRecord,
    SourceRefRole,
    canonical_asset_record_json_schema,
    emit_requirement_gap_records,
    make_lesson_lo_record,
    make_syllabus_requirement_record,
)
from app.marcus.course_source.input_bundle import (
    CoursePlanningProfile,
    LessonPlanningInputBundle,
    ModulePlanningProfile,
    StyleguideResolution,
    build_lesson_planning_input_bundle,
    load_input_bundle,
    load_module_metadata_proposal,
    render_input_bundle_yaml,
    write_input_bundle,
)
from app.marcus.course_source.manifest_drift import ManifestDriftResult, check_manifest_snapshot
from app.marcus.course_source.manifest_scan import (
    CourseSourceScan,
    render_gap_ledger_yaml,
    render_manifest_yaml,
    scan_course,
    write_gap_ledger,
    write_manifest_snapshot,
)
from app.marcus.course_source.models import (
    CourseRecord,
    GapLedger,
    SourceManifest,
    SourceManifestEntry,
)
from app.marcus.course_source.registry import load_course
from app.marcus.course_source.syllabus_metadata import (
    AnchoredObjective,
    AnchoredText,
    CourseMetadataProposal,
    ExtractedSyllabusDocument,
    ModuleMetadataProposal,
    SourceAnchor,
    SyllabusExtractionError,
    build_module_metadata_proposal,
    build_module_metadata_proposal_from_document,
    load_extracted_document_yaml,
    read_docx_syllabus,
    read_mhtml_syllabus,
    read_syllabus,
    render_extracted_document_yaml,
    render_module_metadata_yaml,
)

__all__ = [
    "AnchoredObjective",
    "AnchoredText",
    "CourseRecord",
    "CourseMetadataProposal",
    "CoursePlanningProfile",
    "CourseSourceScan",
    "ExtractedSyllabusDocument",
    "GapLedger",
    "LessonPlanningInputBundle",
    "ManifestDriftResult",
    "ModuleMetadataProposal",
    "ModulePlanningProfile",
    "ASSET_KIND_RECONCILIATION",
    "SCHEMA_VERSION",
    "SourceAnchor",
    "StyleguideResolution",
    "AssetKind",
    "AssetRecordStatus",
    "AssetReview",
    "AssetSourceRef",
    "CanonicalAssetRecord",
    "SourceRefRole",
    "canonical_asset_record_json_schema",
    "emit_requirement_gap_records",
    "make_lesson_lo_record",
    "make_syllabus_requirement_record",
    "SourceManifest",
    "SourceManifestEntry",
    "SyllabusExtractionError",
    "build_lesson_planning_input_bundle",
    "build_module_metadata_proposal",
    "build_module_metadata_proposal_from_document",
    "check_manifest_snapshot",
    "load_extracted_document_yaml",
    "load_course",
    "load_input_bundle",
    "load_module_metadata_proposal",
    "read_docx_syllabus",
    "read_mhtml_syllabus",
    "read_syllabus",
    "render_extracted_document_yaml",
    "render_gap_ledger_yaml",
    "render_input_bundle_yaml",
    "render_manifest_yaml",
    "render_module_metadata_yaml",
    "scan_course",
    "write_gap_ledger",
    "write_input_bundle",
    "write_manifest_snapshot",
]
