"""Emit the Slab 7a gate fold audit manifest."""

from __future__ import annotations

import argparse
import os
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import yaml

from app.manifest.loader import load as load_manifest
from app.manifest.schema import PipelineManifest

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_MANIFEST_PATH = REPO_ROOT / "state" / "config" / "pipeline-manifest.yaml"
DEFAULT_OUTPUT_PATH = REPO_ROOT / "state" / "config" / "gate_fold_manifest.yaml"
DEFAULT_GENERATED_AT = datetime(2026, 4, 29, tzinfo=UTC)


def _generated_at(now: datetime | None) -> str:
    env_value = os.getenv("GATE_FOLD_MANIFEST_GENERATED_AT")
    if env_value:
        return env_value
    effective_now = now or DEFAULT_GENERATED_AT
    if effective_now.tzinfo is None:
        effective_now = effective_now.replace(tzinfo=UTC)
    return effective_now.astimezone(UTC).isoformat().replace("+00:00", "Z")


def gate_fold_entries(manifest: PipelineManifest) -> list[dict[str, str | None]]:
    """Return audit entries for declared gate codes in manifest order."""
    gate_nodes = [node for node in manifest.nodes if node.gate and node.gate_code]
    gate_codes = {str(node.gate_code) for node in gate_nodes}
    fold_map = {
        str(node.gate_code): node.fold_with
        for node in gate_nodes
        if node.fold_with is not None
    }

    for code, target in sorted(fold_map.items()):
        if target not in gate_codes:
            raise ValueError(f"gate {code} folds into unknown gate_code {target}")
        if target == code:
            raise ValueError(f"gate {code} cannot fold into itself")

    for start in sorted(fold_map):
        path: list[str] = []
        current: str | None = start
        while current in fold_map:
            if current in path:
                cycle = " -> ".join([*path[path.index(current) :], current])
                raise ValueError(f"fold cycle detected: {cycle}")
            path.append(current)
            current = fold_map[current]

    entries: list[dict[str, str | None]] = []
    for node in gate_nodes:
        code = str(node.gate_code)
        if node.fold_with is not None:
            entries.append(
                {
                    "code": code,
                    "mechanism": "fold_with",
                    "fold_target": node.fold_with,
                }
            )
        elif node.fold_target is not None:
            entries.append(
                {
                    "code": code,
                    "mechanism": "fold_target",
                    "fold_target": node.fold_target,
                }
            )
        else:
            entries.append(
                {
                    "code": code,
                    "mechanism": "pause_point",
                    "fold_target": None,
                }
            )
    return entries


def render_gate_fold_manifest(
    manifest: PipelineManifest,
    *,
    manifest_path: Path,
    now: datetime | None = None,
) -> str:
    """Render the audit manifest as deterministic YAML text."""
    payload: dict[str, Any] = {"gates": gate_fold_entries(manifest)}
    try:
        source_path = manifest_path.resolve().relative_to(REPO_ROOT).as_posix()
    except ValueError:
        source_path = manifest_path.as_posix()
    body = yaml.safe_dump(
        payload,
        default_flow_style=False,
        sort_keys=False,
        allow_unicode=True,
        line_break="\n",
    )
    header = (
        f"# Auto-generated by Story 7a.2 from {source_path}.\n"
        "# Do NOT hand-edit. Re-emit via `python -m app.manifest.gate_fold_manifest_emit`.\n"
        f"# Generated: {_generated_at(now)}\n"
        f"# Source manifest schema_version: {manifest.schema_version}\n"
    )
    return f"{header}{body}"


def emit_gate_fold_manifest(
    manifest_path: Path = DEFAULT_MANIFEST_PATH,
    output_path: Path = DEFAULT_OUTPUT_PATH,
    *,
    now: datetime | None = None,
) -> None:
    """Load, render, and write the gate fold audit manifest."""
    manifest = load_manifest(manifest_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        render_gate_fold_manifest(manifest, manifest_path=manifest_path, now=now),
        encoding="utf-8",
        newline="\n",
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Emit gate_fold_manifest.yaml.")
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST_PATH)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT_PATH)
    args = parser.parse_args(argv)
    emit_gate_fold_manifest(args.manifest, args.output)
    print(f"gate-fold-manifest emitted: {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
