"""Emit the operator-readable vocabulary glossary (Story 7a.6)."""

from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Any

import yaml

REGISTRY_PATH = (
    Path(__file__).resolve().parents[2]
    / "docs"
    / "conversational-gates"
    / "_registry"
    / "vocabulary.yaml"
)
GLOSSARY_PATH = (
    Path(__file__).resolve().parents[2]
    / "docs"
    / "conversational-gates"
    / "_registry"
    / "glossary.md"
)


def _load_registry(registry_path: Path) -> dict[str, Any]:
    return yaml.safe_load(registry_path.read_text(encoding="utf-8"))


def _render_token_group(group_name: str, tokens: list[str]) -> list[str]:
    lines = [f"### {group_name}", ""]
    lines.extend(f"- `{token}`" for token in tokens)
    lines.append("")
    return lines


def render_glossary(registry: dict[str, Any], *, now: datetime | None = None) -> str:
    """Render glossary markdown from the registry."""
    generated = now.date().isoformat() if now else "deterministic"
    lines = [
        "# Conversational Gate Vocabulary Glossary",
        "",
        "<!-- Auto-generated by `python -m app.models.glossary_emit`; do not hand-edit. -->",
        "",
        f"- Schema version: `{registry['schema_version']}`",
        f"- Generated: `{generated}`",
        "",
    ]
    for namespace_name, namespace in registry["namespaces"].items():
        lines.extend([f"## {namespace_name}", "", namespace["description"], ""])
        for group_name, value in namespace["tokens"].items():
            if isinstance(value, list):
                lines.extend(_render_token_group(group_name, value))
            else:
                lines.extend([f"### {group_name}", "", f"- `{value}`", ""])
    return "\n".join(lines).rstrip() + "\n"


def emit_glossary(
    registry_path: Path = REGISTRY_PATH,
    output_path: Path = GLOSSARY_PATH,
    *,
    now: datetime | None = None,
) -> None:
    """Write the vocabulary glossary."""
    registry = _load_registry(registry_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        render_glossary(registry, now=now),
        encoding="utf-8",
        newline="\n",
    )


def main() -> int:
    emit_glossary()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
