from __future__ import annotations

import ast
from pathlib import Path

from skills.bmad_create_specialist.scripts import generate
from tests.specialists.generator.conftest import TEMP_PYPROJECT
from tests.specialists.generator.conftest import make_request as make_request
from tests.specialists.generator.conftest import temp_repo_root as temp_repo_root


def _read_pyproject(repo_root: Path) -> str:
    return (repo_root / "pyproject.toml").read_text(encoding="utf-8")


def _c3_ignore_imports(pyproject_text: str) -> list[str]:
    marker = "ignore_imports = ["
    start = pyproject_text.index(marker) + len(marker)
    end = pyproject_text.index("]", start)
    body = pyproject_text[start:end]
    values: list[str] = []
    for line in body.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        line = line.split("#", 1)[0].strip().rstrip(",")
        if line:
            values.append(ast.literal_eval(line))
    return values


def test_temp_pyproject_baseline_is_5_rows(temp_repo_root: Path) -> None:
    pyproject = _read_pyproject(temp_repo_root)
    actual = _c3_ignore_imports(pyproject)
    baseline = _c3_ignore_imports(TEMP_PYPROJECT)
    assert len(actual) == 5
    assert set(actual) == set(baseline)


def test_vera_dispatch_wrapper_module_exists_and_imports() -> None:
    from app.specialists.vera.sensory_bridges_dispatch import dispatch_to_sensory_bridges

    assert callable(dispatch_to_sensory_bridges)


def test_post_emit_temp_pyproject_has_vera_row_and_no_duplicate(
    temp_repo_root: Path, make_request
) -> None:
    vera_skill = temp_repo_root / "skills" / "bmad-agent-fidelity-assessor"
    vera_skill.mkdir(parents=True, exist_ok=True)
    (vera_skill / "SKILL.md").write_text("# vera skill", encoding="utf-8")

    generate.generate_specialist(
        make_request(
            name="vera",
            mcp_tool="none",
            expertise_tier="L4-fidelity-assessment",
            from_skill=vera_skill,
            repo_root=temp_repo_root,
            force=True,
        )
    )
    pyproject = _read_pyproject(temp_repo_root)
    target = "app.specialists.vera.graph -> app.gates.resume_api"
    rows = _c3_ignore_imports(pyproject)
    assert target in rows
    assert rows.count(target) == 1
    assert "# generated by bmad-create-specialist for vera" in pyproject
